### ISSUE TITLE
(Hagbound Witch) Vile Curse uses Cha instead of Int

### ISSUE THREAD

**Issue by abishai** [Vek17/WrathMods-TabletopTweaks#2]
Hello, I've filed a bug report to Owlcats, but as you fix 'incorrectly implemented rules', here is another one: Vile Curse uses Cha instead of Int on Hagbound witches, making this feature almost non-functional.

Maybe they will fix this, maybe not.

**Comment by Vek17** [comment]
Given that there is no language specifying it scales with int, this seems technically correct as spell like abilities scale off charisma unless otherwise stated.

**Comment by abishai** [comment]
Vile Curse is Bestow Curse at will, Bestow Curse is a necromancy spell, receiving bonus from casting attrubute (int for hag witches)

**Comment by Vek17** [comment]
Vile curse is Bestow Curse at will as a spell like ability. Spell like abilities use the following to calculate DC unless otherwise stated: 10 + Spell Level + Charisma Modifier. This is also consistent with Hag's spell like abilities they use. It would be better if it scaled off Int, but as written that is not the case.

**Comment by abishai** [comment]
Hmm, I didn't think about Vile Curse from this perspective, nor I familiar with PnP to argue.
I'd say this is dooming the entire archetype as Hags already need Int, Str, Dex and Con. There is no room for another attribute :(
