### ISSUE TITLE
Coup de Grace

### ISSUE THREAD

**Issue by B14d3r11** [Vek17/WrathMods-TabletopTweaks#20]
In the TTRPG Coup de Grace is a Fortitude save DC 10 + damage dealt

In game its set to 10+BAB+Melee Damage Attribute modifier (so Str?) + Weapons Critical Modifier

This makes it a guranteed DC every time so a lvl 5 Rogue Coup de Grace is a DC 20 as opposed to dealing 20 dmg and it being a DC 30

**Comment by Amariithynar** [comment]
It's "melee damage attribute modifier" instead of just "strength modifier" because you can use feats and class features to adjust it to scale from another stat (primarily dex, with things like Fencing Grace or Rogue's Finesse damage class feature, which is basically the feat but class-bound).

Most likely the change was done so that crit-heavy weapons have more of a risk-reward setup while a puny dagger doesn't stand much chance of just insta-gibbing people, unless in the right (read: roguish) hands.

**Comment by Vek17** [comment]
This has been fixed. Coup now scales off weapon damage correctly.
