### ISSUE TITLE
Dynamic Item Naming is overdoing it just a bit.

### ISSUE THREAD

**Issue by pheonix99** [Vek17/WrathMods-TabletopTweaks#306]
This is a really cool feature but some effects that shouldn't enter the names are.

Crusader's Edge adds Evil Outsider Bane to the item name - that's not an item property, it's a buff. I would assume most-to-all other weapon buffs that add an enchant with a name do this too.

Radiance's native Holy-with-Right-User effect is adding Holy to the name - it's part of the sword itself, shouldn't show up.

**Comment by pheonix99** [comment]
Didn't realize this was an optional setting kicking in - suggest defaulting it to not include temp effects.

**Comment by Vek17** [comment]
I thought I actually had that defaulted to off, that was the intent here

**Comment by Vek17** [comment]
Uploaded a new release (no new version) with a more sane default config.

**Comment by Vek17** [comment]
The Holy effect on Radiance is different since it is not considered a temporary effect, but does not exist on the Weapon Blueprint. This means it gets treated as an additional weapon effect that is not part of the base weapon the same way trickster enchants work (which is the main target of this feature).
